### ISSUE TITLE
Number of peptides and PSMs is the same

### ISSUE THREAD

**Issue by ypriverol** [mwalzer/qc-plotter#1]
@mwalzer I'm running the pipeline and I have detected that the number of PSMs and peptides is the same in all cases. IT looks like after applying FDR filtering We get one PSM per peptide ?

**Comment by mwalzer** [comment]
That's exactly right. So when you run the ids through IDFilter or FalseDiscoveryRate tools, you will keep only the top-scoring PSM. To get the right PSM number you'd have to apply the qc-plot before filtering.
